# Generated by Django 6.1 on 2026-08-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Single emoji shown on the card, e.g. 🎯', max_length=10)),
                ('short_description', models.CharField(max_length=160)),
                ('detail_description', models.TextField()),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
